def test_get_manager_returns_all_managers(client):

    # Expected output (generated by src/shifts/app/load_init_data.py)
    # [
    #     {
    #         "username": "Manager1",
    #         "id": 2
    #     }
    # ]

    # Set up
    session, api_url = client
    url = f"{api_url}/managers/"

    # Exercise
    res = session.get(url=url)

    # Verify
    res_json = res.json()
    assert res.status_code == 200
    assert res_json[0]["id"] == 2
    assert res_json[0]["username"] == "Manager1"


def test_get_manager_returns_one_managers(client):

    # Expected output
    # {
    #     "username": "Manager1",
    #     "id": 2
    # }

    # Set up
    session, api_url = client
    url = f"{api_url}/managers/2"

    # Exercise
    res = session.get(url=url)

    # Verify
    res_json = res.json()
    assert res.status_code == 200
    assert res_json["id"] == 2
    assert res_json["username"] == "Manager1"


def test_get_non_existent_manager_returns_404(client):

    # Expected output
    # {'detail': 'Manager not found'}

    # Set up
    session, api_url = client
    url = f"{api_url}/managers/1"

    # Exercise
    res = session.get(url=url)

    # Verify
    res_json = res.json()
    print(res_json)
    assert res.status_code == 404
    assert res_json["detail"] == "Manager not found"
