from datetime import date


def test_get_worker_returns_all_workers(client):

    # Expected output (generated by src/shifts/app/load_init_data.py)
    # [{
    #   "username":"Worker1",
    #   "id":1,
    #   "shifts":[{
    #       "worker_id":1,
    #       "shift_id":1,
    #       "shift_date":"2022-06-24"
    #   }]
    # }]

    # Set up
    session, api_url = client
    url = f"{api_url}/workers/"

    # Exercise
    res = session.get(url=url)

    # Verify
    res_json = res.json()
    assert res.status_code == 200
    assert res_json[0]["id"] == 1
    assert res_json[0]["username"] == "Worker1"
    assert res_json[0]["shifts"][0]["worker_id"] == 1
    assert res_json[0]["shifts"][0]["shift_id"] == 1
    assert res_json[0]["shifts"][0]["shift_date"] == date.today().strftime("%Y-%m-%d")


def test_get_worker_returns_one_workers(client):

    # Expected output
    # {
    #   "username":"Worker1",
    #   "id":1,
    #   "shifts":[{
    #       "worker_id":1,
    #       "shift_id":1,
    #       "shift_date":"2022-06-24"
    #   }]
    # }

    # Set up
    session, api_url = client
    url = f"{api_url}/workers/1"

    # Exercise
    res = session.get(url=url)

    # Verify
    res_json = res.json()
    assert res.status_code == 200
    assert res_json["id"] == 1
    assert res_json["username"] == "Worker1"
    assert res_json["shifts"][0]["worker_id"] == 1
    assert res_json["shifts"][0]["shift_id"] == 1
    assert res_json["shifts"][0]["shift_date"] == date.today().strftime("%Y-%m-%d")


def test_get_non_existent_worker_returns_404(client):

    # Expected output
    # {'detail': 'Worker not found'}

    # Set up
    session, api_url = client
    url = f"{api_url}/workers/2"

    # Exercise
    res = session.get(url=url)

    # Verify
    res_json = res.json()
    print(res_json)
    assert res.status_code == 404
    assert res_json["detail"] == "Worker not found"


def test_get_shifts_for_worker_returns_shifts(client):

    # Expected output
    # {[
    #   {
    #       "id": 1,
    #       "shift_date": "2022-06-24"
    #       "shift_slot": 1,
    #   }
    # ]}

    # Set up
    session, api_url = client
    url = f"{api_url}/workers/1/shifts"

    # Exercise
    res = session.get(url=url)
    res_json = res.json()

    # Verify
    res_json = res.json()
    assert res.status_code == 200
    assert res_json[0]["id"] == 1
    assert res_json[0]["shift_date"] == date.today().strftime("%Y-%m-%d")
    assert res_json[0]["shift_slot"] == 1
