# .github/workflows/test.yml
name: heroku deploy
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python && \
          cd /usr/local/bin && \
          ln -s /opt/poetry/bin/poetry && \
          poetry config virtualenvs.create false

      - name: Install dependencies and run tests
        working-directory: ./src/shifts
        run: |
          poetry install --no-root && \
          poetry run pytest -v

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Build docker image
        working-directory: ./
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          make build-app-heroku

      - name: Push docker image to registry
        working-directory: ./
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          make push-app-heroku

      - name: Check out repository code
        working-directory: ./
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          make release-heroku
